#file: noinspection YAMLSchemaValidation
version: '3'

services:

  backend:
    depends_on:
      - database
      - start-minio
    restart: on-failure
    ports:
      - "7000:7000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./config/config.yaml:/app/config/config.yaml"
    extra_hosts:
      - host.docker.internal:host-gateway

  database:
    image: mongo:latest
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root-user
      MONGO_INITDB_ROOT_PASSWORD: root-pwd

  mongo-express:
    image: mongo-express:latest
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root-user
      ME_CONFIG_MONGODB_ADMINPASSWORD: root-pwd
      ME_CONFIG_MONGODB_URL: mongodb://root-user:root-pwd@database:27017/
    extra_hosts:
      - host.docker.internal:host-gateway

  gorse:
    image: zhenghaoz/gorse-in-one
    restart: unless-stopped
    ports:
      - "8086:8086"   # gRPC port
      - "8088:8088"   # HTTP port
    command: >
      -c /etc/gorse/config.toml 
      --log-path /var/log/gorse/master.log 
      --cache-path /var/lib/gorse/master_cache.data
    volumes:
      # Mount the configuration file.
      - ./config/gorse.config.toml:/etc/gorse/config.toml
    extra_hosts:
      - host.docker.internal:host-gateway

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9090"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-storage:/data
    ports:
      - 9000:9000
      - 9090:9090

  start-minio:
    depends_on:
      - minio
    image: golang:buster
    command: /api/scripts/wait-for-it/wait-for-it.sh minio:9000 -t 120 -- /api/scripts/setup-minio.sh
    extra_hosts:
      - host.docker.internal:host-gateway

volumes:
  minio-storage: {}