MONGO_URI: "mongodb://root-user:root-pwd@database:27017/"
DATABASE_NAME: werr
GORSE_URL: "http://localhostse:8088"
GORSE_APIKEY: ""
S3_ACCESS_KEY: "minioadminaccesskey"
S3_SECRET_KEY: "minioadminsecretkey"
S3_ENDPOINT: "http://minio:9000"
S3_BUCKET: "werr"
S3_REGION: "us-east-1"